name: Add Labels

on:
  pull_request:
    types: [opened, edited]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains( fromJson('[ "tomalaforge" ]'), github.actor ) }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: supporter
