name: Add Labels

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  add_supporters:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i @actions/core @actions/github

      - name: Add labels
        uses: ./.github/github-action/
        with:
          github_token: ${{ secrets.github_token }}
