name: updates Labels

on:
  pull_request_target:
    types: [ edited ]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'sponsor') ||
      contains(github.event.issue.labels.*.name, 'contributor')
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: to be reviewed/update
