name: Label supporter

on:
  issues:
    types: [opened, edited]

jobs:
  add_label_tier_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        if:
          ${{ contains( fromJson('[ "tomalaforge" ]'), github.actor ) }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: supporter
